services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn 'app:create_app()'"
    workingDir: server
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: your-render-db-url


